spring.application.name=azure-jvm-observatory
server.port=8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus,threaddump,heapdump
management.endpoint.health.show-details=always
management.metrics.tags.application=azure-jvm-observatory